# Generated by Django 5.1.15 on 2026-09-07 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del ítem')),
                ('tipo', models.CharField(choices=[('PLATO', 'Plato Principal'), ('BEBIDA', 'Bebida')], default='PLATO', max_length=10, verbose_name='Tipo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio ($)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción gastronómica')),
                ('icono', models.CharField(default='🍽️', max_length=20, verbose_name='Emoji o Ícono')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ítem de Menú',
                'verbose_name_plural': 'Ítems del Menú',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('mesa', models.PositiveSmallIntegerField(default=1, verbose_name='Número de Mesa')),
                ('notas', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas del Mozo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (En Comanda)'), ('PREPARANDO', 'En Preparación (Cocinando)'), ('SERVIDO', 'Servido a la Mesa')], default='PENDIENTE', max_length=15, verbose_name='Estado de la Orden')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Hora del Pedido')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bebida', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'BEBIDA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_bebida', to='restaurante.menu', verbose_name='Bebida Típica')),
                ('plato', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PLATO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_plato', to='restaurante.menu', verbose_name='Plato Típico')),
            ],
            options={
                'verbose_name': 'Pedido / Comanda',
                'verbose_name_plural': 'Pedidos / Comandas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
